In [1]:
from sklearn.pipeline import Pipeline
#feature scaling
from sklearn.preprocessing import StandardScaler 
from sklearn.linear_model import LogisticRegression

In [2]:
steps=[("standard_Scaler",StandardScaler()),
      ("classifier",LogisticRegression())]

In [3]:
steps


[('standard_Scaler', StandardScaler()), ('classifier', LogisticRegression())]

In [14]:
pipe=Pipeline(steps)

In [5]:
##visulizate pipeline set_config
from sklearn import set_config

In [6]:
set_config(display="diagram")

In [7]:
pipe


Pipeline(steps=[('standard_Scaler', StandardScaler()),
                ('classifier', LogisticRegression())])

In [8]:
#creating a data set using sklearn
from sklearn.datasets import make_classification
x,y=make_classification(n_samples=200)

In [9]:
x.shape

(200, 20)

In [10]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.33,random_state=1)
X_train

array([[-3.60791626e-01,  2.18680741e+00,  1.69330196e-03, ...,
         2.84550214e-01,  1.50349867e+00,  1.45561993e+00],
       [-7.00482699e-01,  5.30525603e-01, -8.42170368e-01, ...,
         1.32724458e-01,  8.67428072e-01,  1.04132681e+00],
       [-9.35495006e-01,  3.80755213e-01,  6.71802438e-01, ...,
        -1.04066380e+00, -8.45267368e-01,  2.84187401e-01],
       ...,
       [ 9.10426683e-01, -2.74987118e-02, -2.54995574e+00, ...,
        -9.49371154e-01, -1.75032638e+00, -4.66983290e-01],
       [ 1.49824368e-01,  6.05448176e-01, -4.95220398e-01, ...,
        -5.30771623e-01, -2.69245344e-01, -9.13091690e-01],
       [-8.82334147e-01, -8.75475541e-01,  2.21023598e-01, ...,
         5.08815462e-01, -7.87933397e-01, -1.16099304e+00]])

In [11]:
pipe.fit(X_train,y_train)

Pipeline(steps=[('standard_Scaler', StandardScaler()),
                ('classifier', LogisticRegression())])

In [12]:
y_pred=pipe.predict(X_test)

In [13]:
y_pred

array([0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1,
       1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1])

In [46]:
#qn--combing more and more models  and the techniques

In [17]:
from sklearn.decomposition import PCA
from sklearn.svm import SVC

In [36]:
steps=[("scaling",StandardScaler()),
       ("PCA",PCA(n_components=3)),
       ("SVC",SVC())]

In [37]:
steps

[('scaling', StandardScaler()), ('PCA', PCA(n_components=3)), ('SVC', SVC())]

In [38]:
pipe2=Pipeline(steps)

In [39]:
pipe2

Pipeline(steps=[('scaling', StandardScaler()), ('PCA', PCA(n_components=3)),
                ('SVC', SVC())])

In [41]:
pipe2['scaling'].fit_transform(X_train)

array([[-0.41967873,  2.57230055,  0.05650491, ...,  0.3865979 ,
         1.1012259 ,  1.42817167],
       [-0.74711139,  0.61408669, -0.7987283 , ...,  0.22889889,
         0.61674599,  1.03163823],
       [-0.97364282,  0.43701389,  0.73564256, ..., -0.9898809 ,
        -0.68777358,  0.30695543],
       ...,
       [ 0.8056652 , -0.04566272, -2.52952301, ..., -0.89505667,
        -1.3771356 , -0.41201451],
       [ 0.0725107 ,  0.70266728, -0.44710381, ..., -0.46026398,
        -0.24903124, -0.8389994 ],
       [-0.92240037, -1.04822157,  0.27879029, ...,  0.61953866,
        -0.64410365, -1.07627386]])

In [42]:
pipe2.fit(X_train,y_train)

Pipeline(steps=[('scaling', StandardScaler()), ('PCA', PCA(n_components=3)),
                ('SVC', SVC())])

In [45]:
pipe2.predict(X_test)

array([0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1])

In [47]:
#Qn-3 column transformeer

In [58]:
#numerical processing
num_col=Pipeline(steps=[("imputation mean",SimpleImputer(missing_values=np.nan,strategy="mean")),
                        ("scaler",StandardScaler())]
                )

In [59]:
num_col

Pipeline(steps=[('imputation mean', SimpleImputer()),
                ('scaler', StandardScaler())])

In [61]:
#categorical processing
from sklearn.preprocessing import OneHotEncoder
cate_pro=Pipeline(steps=[("imputation constant",SimpleImputer(fill_value="mssing",strategy="constant")),
                        ("onehot",OneHotEncoder(handle_unknown="ignore"))]
                 )

In [63]:
cate_pro

Pipeline(steps=[('imputation constant',
                 SimpleImputer(fill_value='mssing', strategy='constant')),
                ('onehot', OneHotEncoder(handle_unknown='ignore'))])

In [65]:
#combing processing techniques
from sklearn.compose import ColumnTransformer

In [74]:
preprocessor=ColumnTransformer([("categorical_processor",["gender","city","nmame"]),
                  ("numerical",num_col,["age","height","sex"])]


)

In [75]:
preprocessor

ValueError: not enough values to unpack (expected 3, got 2)

ValueError: not enough values to unpack (expected 3, got 2)

ColumnTransformer(transformers=[('categorical_processor',
                                 ['gender', 'city', 'nmame']),
                                ('numerical',
                                 Pipeline(steps=[('imputation mean',
                                                  SimpleImputer()),
                                                 ('scaler', StandardScaler())]),
                                 ['age', 'height', 'sex'])])

In [80]:
from sklearn.pipeline import make_pipeline

In [81]:
pipe=make_pipeline(preprocessor,LogisticRegression())

In [82]:
pipe

ValueError: not enough values to unpack (expected 3, got 2)

ValueError: not enough values to unpack (expected 3, got 2)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('categorical_processor',
                                                  ['gender', 'city', 'nmame']),
                                                 ('numerical',
                                                  Pipeline(steps=[('imputation '
                                                                   'mean',
                                                                   SimpleImputer()),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['age', 'height', 'sex'])])),
                ('logisticregression', LogisticRegression())])